title: Jennysloth
description: "Applied Mathematics/Program/Invest/Music(Clarinet)"
locale: zh-TW
baseurl: ""
url: "https://jennysloth.github.io"
author: Lin, Chen-Ling
email: linchenling233@gmail.com  

remote_theme: jeffreytse/jekyll-theme-yat
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
exclude:
  - README.md

collections:
  posts:
    output: true

include:
  - _pages

header_pages:
  - _pages/about.md
  - _pages/courses.md
  - _pages/posts.md

# 文章輸出
paginate: 5
paginate_path: "/posts/page:num"

nav:
  - name: 關於
    link: /about/
  - name: 課程紀錄
    link: /courses/
  - name: 隨記
    link: /posts/
  - name: 寶寶專區
    link: /baby/

sass:
  style: compressed