title: Jennysloth
description: "Applied Mathematics/Program/Invest/Music(Clarinet)"
locale: zh-TW
baseurl: ""
url: "https://jennysloth.github.io"
author: Lin, Chen-Ling
email: linchenling233@gmail.com  

remote_theme: erlzhang/jekyll-theme-persephone
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
exclude:
  - README.md

include:
  - _posts

collections:
  posts:
    output: true

include:
  - _pages

nav:
  - name: 關於
    link: /about/
  - name: 課程紀錄
    link: /courses/
  - name: 隨記
    link: /posts/